### ISSUE TITLE
All dates

### ISSUE THREAD

**Issue by gruberpeter** [montemurroPaolo/django_autograder#18]
- picker shows gg/mm/yyyy, but internally (when entered manually) we have yyyy-mm-dd
- does the format depend on the locale (and is this a good idea?)
- add a date picker WITH time picker, see screenshot
- really like the "NOW" button, saves so much time

![Screen Shot 2021-03-04 at 18 08 14](https://user-images.githubusercontent.com/42358482/110001377-9eaeb600-7d14-11eb-832c-18285a60a534.png)
![Screen Shot 2021-03-04 at 18 07 21](https://user-images.githubusercontent.com/42358482/110001382-9f474c80-7d14-11eb-9b8a-730e046ab587.png)

**Comment by sim55649** [comment]
for the 'date picker' in the creation of an assignment, I made sure that it goes by default to retrieve the current date and time in order to do not make it necessary to use a "now" button. 
needs to be tested, I will close the issue once the tests are done.
![immagine](https://user-images.githubusercontent.com/64262053/110382008-9a5b0380-805a-11eb-9dc9-8142ff4d6d7c.png)

**Comment by sim55649** [comment]
solved with last version
